### ISSUE TITLE
mini game ataque  - inseticida

### ISSUE THREAD

**Issue by thecarlosneto** [thecarlosneto/projeto-integrador-II#10]
insecticida se atingir - mosquito morre

**Comment by voidzlinguiceta** [comment]
Implementação da imagem "spray" para criação do inseticida. Defini também sua colisão com o player_mosquito (colisao = GAME_OVER).
Adicionei uma variavel a mais tbm para a "suavização" de movimentação, dando um aspecto de velocidade suavizada em spray.y = player_mosquito.y.
