### ISSUE TITLE
mini game ataque  - mão

### ISSUE THREAD

**Issue by thecarlosneto** [thecarlosneto/projeto-integrador-II#11]
mão parábola - mosquito vai para um estagio para trás (três estágios morre)

**Comment by mofologico** [comment]
Foram criadas 5 funções com padrões de movimento para a mão, lugares aleatórios de onde a mão vem e velocidade aleatória também. Mas mesmo assim persiste o erro da aceleração com o mouse que não consigo resolver, pelo menos descobri que esta afetando qualquer objeto em tela. Faltam imagens para os placeholders e a imagem do background.
