### ISSUE TITLE
mini game ataque - teia

### ISSUE THREAD

**Issue by thecarlosneto** [thecarlosneto/projeto-integrador-II#12]
obstáculo que percorre da direita para esquerda

- escolhe um Y aleatório para spawn
- para a colisão, usar a função `colisaoQuadradoDentro()` (já feita)
- se colidir, perde 1 vida (vai mais pra trás)

**Comment by voidzlinguiceta** [comment]
Nesse código tbm fiz mudança em relação a "perda de vida" do mosquito, tendo em vista que possamos fazer o game over em um x != 0, levando então a ideia do inseticida (que estaria ali mais ou menos em x=50 por ai) pra frente .

Antes, a cada hit na mão (e agora consequentemente na teia), o mosquito recuava x=-200, agora, o mesmo retorna somente x=-100.

**Comment by voidzlinguiceta** [comment]
Atualização: Implementei o sistema de colisao da teia e da mão na função colisaoCirculoDentro() e está funcionando.
