### ISSUE TITLE
fazer moodboard

### ISSUE THREAD

**Issue by thecarlosneto** [thecarlosneto/projeto-integrador-II#21]
- [Link para o moodboard (canva)](https://www.canva.com/design/DAGRo9KRR6Q/Fd1EgLr0FTRXVkg5y6Y6Zg/edit)

- [Vídeo da personagem no moodboard para inspiração](https://www.youtube.com/watch?v=Td7CBNu0914)
(a personagem ENA é, na verdade, um vírus de computador também, por isso a relevância; a estética meio pixelada/ resolução baixa é interessante para o jogo)

**Comment by joaoarapucas** [comment]
ainda preciso mostrar para o resto do grupo como ficou o moodboard (imagem pra inspirações e noções pra estética do jogo)
