### ISSUE TITLE
mini game fagocitose - Criar o sistema de colisão, ao passo que a circunferência do círculo principal cresça ao colidir com os círculos menores com posições aleatórias

### ISSUE THREAD

**Issue by thecarlosneto** [thecarlosneto/projeto-integrador-II#3]

**Comment by joaoarapucas** [comment]
Por mais que a colisão esteja pronta e funcional, ela não é eficiente para o nosso uso em específico; como há vários objetos na tela, ele checa objeto por objeto. Preciso discutir com os professores entre qual algoritmo pra colisão seguir (quadtree ou hashing)
