### ISSUE TITLE
mini game ataque_mosquito - barra de progresso

### ISSUE THREAD

**Issue by thecarlosneto** [thecarlosneto/projeto-integrador-II#52]

**Comment by voidzlinguiceta** [comment]
Implementação da barra de progresso feita mediante o calculo de (tempo_segundos/tempo_max), totalizando 20 segundos de gameplay.
Quando tivermos a tela de vitória, ao chegar no limite maximo da barra de progresso (760) ou ao passar 20 segundos, a tela então aparece, vencendo o jogo.
