### ISSUE TITLE
mini game ataque  - jogador

### ISSUE THREAD

**Issue by thecarlosneto** [thecarlosneto/projeto-integrador-II#8]
criar mosquito movido pelo mouse

**Comment by thecarlosneto** [comment]
Como discutido em grupo, o jogador será movido através das teclas do teclado.

**Comment by mofologico** [comment]
Concluído a parte de movimentação utilizando o teclado, porém quando o mouse se mexe dentro da janela do jogo a aceleração aumenta por algum motivo. Mesmo ignorando eventos que utilizam o mouse e depurando em outras partes do código que utilizam o mouse, como no Viremia.
